
# GET http://localhost:3000/messages

# # Create a new message
POST http://localhost:3000/messages HTTP/1.1
Content-Type: application/json

{
    "content": "Hello World"
}


# # Get a specific message

# GET http://localhost:3000/messages/228

